apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql-pv
    tier: database
    type: jenkins-server
spec:
  storageClassName: jenkins-server
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: mysql-pv-claim
  gcePersistentDisk:
    pdName: jenkins-server
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-pv-claim
    tier: database
spec:
  storageClassName: jenkins-server
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi