apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootserver
spec:
  selector:
    matchLabels:
      app: charity
  replicas: 1
  template:
    metadata:
      labels:
        app: charity
    spec:
      containers:
        - name: springbootserver
          image: lephilong1907/springbootserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              valueFrom :
                configMapKeyRef :
                  name : mysql-config
                  key :  host
            - name: DB_NAME
              valueFrom :
                configMapKeyRef :
                  name : mysql-config
                  key :  dbName
            - name: DB_USERNAME
              valueFrom :
                secretKeyRef :
                  name : mysql-secret
                  key :  username
            - name: DB_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : mysql-secret
                  key :  password